@startuml
'https://plantuml.com/class-diagram

class Issuer <<Address>>
class Minter <<Address>>
note left: Is also Issuer\nwhen no transfer\non creation

class Collection <<Entity>> {
    string id
    int max
    string issuer
    string symbol
    string uri
    Property[] nftProperties
}
class CollectionMetaData {
    string name
    string description
    string externalUri
    string mediaUri
    Property[] properties
}
class NFT <<Entity>> {
    Property[] properties

}

class NFTMetaData {
    Property[] nftProperties
}

class Base <<Entity>>

class Property {
    string name
    PropertyType type
    string value
}

enum PropertyType {
    int
    string
    float
    array
    object
}

Issuer - Collection : hasIssued >
Minter - Collection : hasMinted >
Minter -- Issuer: transferOwnership >
Collection  *-- "1" CollectionMetaData : hasMetaData
Collection - "*" Property: hasProps >
CollectionMetaData - "*" Property: hasProps >
Collection *- "*" NFT
NFT - "*" Property: hasProps >
NFT  *-- "1" NFTMetaData : hasMetaData
Property "*"- NFTMetaData : hasProps <








@enduml